spring:
  application:
    name: agent-mcp-client
  ai:
    mcp:
      client:
        connections:
          agent-mcp-server:
            url: http://localhost:8082

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        ai: DEBUG
