spring:
  application:
    name: agent-mcp-client
  ai:
    openai:
      api-key: ${LLM_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo-0125
    mcp:
      client:
        connections:
          agent-mcp-server:
            url: ${SERVER_URL}

server:
  port: 8083

logging:
  level:
    org:
      springframework:
        ai: DEBUG
