spring:
  application:
    name: agent-mcp-server
  ai:
    mcp:
      server:
        name: agent-mcp-server
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}

  data:
    redis:
      host: ${REDIS_HOST}
      port: REDIS_PORT

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        ai: DEBUG