services:
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
    ports:
      - "8082:8082"
    depends_on:
      - redis
    networks:
      - my-network

  redis:
    image: redis:7.2
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge

volumes:
  redis-data: